---
- hosts: localhost
  become: True
  tasks:
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: Start the container
      docker_container:
        name: devops_scientific_calculator
        image: "av99/devops_scientific_calculator:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:9000:9000
