---
- hosts: localhost
  become: True
  tasks:
    - name: Start the container
      docker_container:
        name: devops_scientific_calculator
        image: "av99/devops_scientific_calculator:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0.8080:9000
